# name: Release to Repo B

# on:
#   workflow_dispatch:

# jobs:
#   release:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repoA
#         uses: actions/checkout@v4

#       - name: Get latest release info
#         id: get_release
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const response = await github.rest.repos.getLatestRelease({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#             });
#             core.setOutput("tag_name", response.data.tag_name);
#             core.setOutput("body", response.data.body);

#       - name: Create Release in repoB
#         uses: softprops/action-gh-release@v1
#         with:
#           token: ${{ secrets.CROSS_REPO_SECRET }}
#           repository: felixcheng/testing
#           tag_name: ${{ steps.get_release.outputs.tag_name }}
#           name: Release ${{ steps.get_release.outputs.tag_name }}
#           body: ${{ steps.get_release.outputs.body }}
#           draft: false
#           prerelease: false

name: Push Release to External Repo
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  push-release:
    runs-on: ubuntu-latest
    steps:
      - name: Push to External Repository
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.CROSS_REPO_TOKEN }}
          repository: felixcheng/testing
          tag_name: ${{ github.event.release.tag_name || 'v1.0.0' }}
          name: ${{ github.event.release.name || 'Release v1.0.0' }}
          body: |
            ${{ github.event.release.body || 'Release notes not available' }}

            ---
            *Pushed from felixpaypal/repoTesting*
          draft: false
          prerelease: ${{ github.event.release.prerelease || false }}
